# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyManager' do

  use_frameworks!

pod 'SnapKit', '~> 5.0.0'
pod 'SDWebImage', '~> 5.0'
pod 'Floaty', '~> 4.2.0'

end
